/*
    Use of LLM:

    Much of the following code was generated by an LLM. I started by refining the 
    design alongside an LLM, then implementing the code myself, but as the time constraint
    became more of a concern, it shifted more towards me specifying the policy, and the LLM
    implementing the mechanism.
*/

#include "Scheduler.hpp"

#include <algorithm>
#include <limits>
#include <unordered_map>

namespace {

constexpr double kOverloadThreshold = 0.80;
constexpr double kUnderloadThreshold = 0.25;
constexpr unsigned kMinReadyMachinesPerCpu = 3;
constexpr unsigned kMinReadyPreferredMachinesPerCpu = 8;
constexpr unsigned kMinReadyGpuMachinesPerCpu = 4;
constexpr Time_t kProtectionWindow = 5'000'000;
constexpr Time_t kIdleSleepDelay = 2'000'000;
constexpr Time_t kPreferredIdleSleepDelay = 10'000'000;
constexpr Time_t kColdShutdownDelay = 20'000'000;
constexpr bool kEnableIdleSleep = true;
constexpr unsigned kPreferredTierReserveDivisor = 4;

uint64_t MachineCapacityScore(MachineId_t machine_id) {
    MachineInfo_t machine_info = Machine_GetInfo(machine_id);
    unsigned base_mips = machine_info.performance.empty() ? 0 : machine_info.performance[0];
    return static_cast<uint64_t>(machine_info.num_cpus) * base_mips;
}

double MachineLoadScore(MachineId_t machine_id) {
    MachineInfo_t machine_info = Machine_GetInfo(machine_id);
    double task_pressure = static_cast<double>(machine_info.active_tasks) /
                           std::max(1u, machine_info.num_cpus);
    double memory_pressure = static_cast<double>(machine_info.memory_used) /
                             std::max(1u, machine_info.memory_size);
    return std::max(task_pressure, memory_pressure);
}

bool ShouldReservePreferredCapacityForSla1(SLAType_t task_sla,
                                           bool machine_is_preferred,
                                           bool machine_already_hosts_sla0,
                                           unsigned preferred_machines,
                                           unsigned preferred_sla0_machines) {
    if(task_sla != SLA0 || !machine_is_preferred) {
        return false;
    }
    if(machine_already_hosts_sla0) {
        return false;
    }
    if(preferred_machines <= 1) {
        return false;
    }

    unsigned reserved_for_non_sla0 = max(1u, preferred_machines / kPreferredTierReserveDivisor);
    return preferred_sla0_machines + reserved_for_non_sla0 >= preferred_machines;
}

bool ShouldAvoidMixedSlaMachine(const unordered_map<MachineId_t, array<unsigned, NUM_SLAS>> & machine_sla_vm_counts,
                                TaskId_t task_id,
                                MachineId_t machine_id) {
    auto counts_it = machine_sla_vm_counts.find(machine_id);
    if(counts_it == machine_sla_vm_counts.end()) {
        return false;
    }

    SLAType_t task_sla = RequiredSLA(task_id);
    if(task_sla == SLA0) {
        return counts_it->second[SLA1] > 0;
    }
    if(task_sla == SLA1) {
        return counts_it->second[SLA0] > 0;
    }
    return false;
}

int PlacementBucket(bool machine_is_preferred,
                    bool reserve_preferred_capacity,
                    bool avoid_mixed_sla_machine,
                    bool is_overloaded,
                    bool is_protected) {
    int bucket = 0;
    if(is_protected) {
        bucket += 4;
    } else if(is_overloaded) {
        bucket += 2;
    }
    if(!machine_is_preferred) {
        bucket += 1;
    }
    if(reserve_preferred_capacity) {
        bucket += 3;
    }
    if(avoid_mixed_sla_machine) {
        bucket += 3;
    }
    return bucket;
}

Priority_t PriorityForTask(TaskId_t task_id) {
    switch(RequiredSLA(task_id)) {
        case SLA0:
            return HIGH_PRIORITY;
        case SLA1:
            return MID_PRIORITY;
        case SLA2:
        case SLA3:
        default:
            return LOW_PRIORITY;
    }
}

bool IsMachineReady(MachineId_t machine_id) {
    return Machine_GetInfo(machine_id).s_state == S0;
}

bool HasMachineMemoryForTask(MachineId_t machine_id, TaskId_t task_id, bool creating_vm) {
    MachineInfo_t machine_info = Machine_GetInfo(machine_id);
    unsigned needed_memory = GetTaskMemory(task_id) + (creating_vm ? VM_MEMORY_OVERHEAD : 0);
    return machine_info.memory_used + needed_memory <= machine_info.memory_size;
}

double ProjectedLoad(MachineId_t machine_id, TaskId_t task_id, bool creating_vm) {
    MachineInfo_t machine_info = Machine_GetInfo(machine_id);
    double projected_tasks = static_cast<double>(machine_info.active_tasks + 1) /
                             std::max(1u, machine_info.num_cpus);
    unsigned projected_memory = machine_info.memory_used + GetTaskMemory(task_id) +
                                (creating_vm ? VM_MEMORY_OVERHEAD : 0);
    double memory_pressure = static_cast<double>(projected_memory) /
                             std::max(1u, machine_info.memory_size);
    return std::max(projected_tasks, memory_pressure);
}

bool IsPreferredMachineForCpu(const unordered_map<CPUType_t, uint64_t> & best_capacity_by_cpu,
                              const MachineInfo_t & machine_info) {
    auto best_it = best_capacity_by_cpu.find(machine_info.cpu);
    uint64_t best_score = (best_it == best_capacity_by_cpu.end()) ? 0 : best_it->second;
    if(best_score == 0) {
        return true;
    }
    unsigned base_mips = machine_info.performance.empty() ? 0 : machine_info.performance[0];
    uint64_t machine_score = static_cast<uint64_t>(machine_info.num_cpus) * base_mips;
    return machine_score * 100 >= best_score * 75;
}

}  // namespace

Scheduler::HostState Scheduler::ClassifyMachine(MachineId_t machine_id) const {
    double load_score = MachineLoadScore(machine_id);

    if(load_score >= kOverloadThreshold) {
        return HostState::OVERLOADED;
    }
    if(load_score <= kUnderloadThreshold) {
        return HostState::UNDERLOADED;
    }
    return HostState::NORMAL;
}

void Scheduler::RefreshMachineStates() {
    host_states.clear();
    for(MachineId_t machine_id : machines) {
        host_states[machine_id] = ClassifyMachine(machine_id);
    }
}

bool Scheduler::TryPlaceTask(TaskId_t task_id, bool log_failure) {
    RefreshMachineStates();
    Priority_t priority = PriorityForTask(task_id);
    CPUType_t required_cpu = RequiredCPUType(task_id);
    VMType_t required_vm = RequiredVMType(task_id);
    SLAType_t required_sla = RequiredSLA(task_id);
    unsigned required_memory = GetTaskMemory(task_id);
    VMId_t best_existing_vm = numeric_limits<VMId_t>::max();
    int best_existing_bucket = numeric_limits<int>::max();
    double best_existing_load = numeric_limits<double>::max();
    Time_t now = Now();
    unordered_map<MachineId_t, MachineInfo_t> machine_infos;
    unordered_map<MachineId_t, bool> machine_is_preferred;
    machine_infos.reserve(machines.size());
    machine_is_preferred.reserve(machines.size());

    unsigned preferred_machines = 0;
    unsigned preferred_sla0_machines = 0;
    for(MachineId_t machine_id : machines) {
        MachineInfo_t machine_info = Machine_GetInfo(machine_id);
        machine_infos.emplace(machine_id, machine_info);

        bool is_preferred = true;
        auto best_it = best_capacity_by_cpu.find(required_cpu);
        uint64_t best_score = (best_it == best_capacity_by_cpu.end()) ? 0 : best_it->second;
        if((required_sla == SLA0 || required_sla == SLA1) &&
           machine_info.cpu == required_cpu &&
           best_score != 0) {
            unsigned base_mips = machine_info.performance.empty() ? 0 : machine_info.performance[0];
            uint64_t machine_score = static_cast<uint64_t>(machine_info.num_cpus) * base_mips;
            is_preferred = machine_score * 100 >= best_score * 75;
        }
        machine_is_preferred[machine_id] = is_preferred;

        if(machine_info.cpu == required_cpu && is_preferred) {
            preferred_machines++;
            auto counts_it = machine_sla_vm_counts.find(machine_id);
            if(counts_it != machine_sla_vm_counts.end() && counts_it->second[SLA0] > 0) {
                preferred_sla0_machines++;
            }
        }
    }

    auto has_machine_memory_for_task = [&](MachineId_t machine_id, bool creating_vm) {
        const MachineInfo_t & machine_info = machine_infos.at(machine_id);
        unsigned needed_memory = required_memory + (creating_vm ? VM_MEMORY_OVERHEAD : 0);
        return machine_info.memory_used + needed_memory <= machine_info.memory_size;
    };

    auto projected_load = [&](MachineId_t machine_id, bool creating_vm) {
        const MachineInfo_t & machine_info = machine_infos.at(machine_id);
        double projected_tasks = static_cast<double>(machine_info.active_tasks + 1) /
                                 std::max(1u, machine_info.num_cpus);
        unsigned projected_memory = machine_info.memory_used + required_memory +
                                    (creating_vm ? VM_MEMORY_OVERHEAD : 0);
        double memory_pressure = static_cast<double>(projected_memory) /
                                 std::max(1u, machine_info.memory_size);
        return std::max(projected_tasks, memory_pressure);
    };

    auto placement_bucket_for_machine = [&](MachineId_t machine_id) {
        auto counts_it = machine_sla_vm_counts.find(machine_id);
        bool machine_already_hosts_sla0 = counts_it != machine_sla_vm_counts.end() &&
                                          counts_it->second[SLA0] > 0;
        bool reserve_preferred_capacity = ShouldReservePreferredCapacityForSla1(required_sla,
                                                                               machine_is_preferred.at(machine_id),
                                                                               machine_already_hosts_sla0,
                                                                               preferred_machines,
                                                                               preferred_sla0_machines);
        bool avoid_mixed = ShouldAvoidMixedSlaMachine(machine_sla_vm_counts, task_id, machine_id);
        return PlacementBucket(machine_is_preferred.at(machine_id),
                               reserve_preferred_capacity,
                               avoid_mixed,
                               host_states[machine_id] == HostState::OVERLOADED,
                               IsMachineProtected(machine_id, now));
    };

    for(VMId_t vm_id : vms) {
        VMInfo_t vm_info = VM_GetInfo(vm_id);
        auto vm_sla_it = vm_slas.find(vm_id);
        if(vm_info.cpu != required_cpu ||
           vm_info.vm_type != required_vm ||
           (vm_sla_it != vm_slas.end() && vm_sla_it->second != required_sla)) {
            continue;
        }
        MachineId_t machine_id = vm_info.machine_id;
        const MachineInfo_t & machine_info = machine_infos.at(machine_id);
        if(pending_state_changes.count(machine_id) != 0 ||
           machine_info.s_state != S0 ||
           !has_machine_memory_for_task(machine_id, false)) {
            continue;
        }
        double vm_projected_load = projected_load(machine_id, false);

        int bucket = placement_bucket_for_machine(machine_id);
        if(vm_projected_load <= kOverloadThreshold) {
            bucket = max(0, bucket - 1);
        }

        if(bucket < best_existing_bucket ||
           (bucket == best_existing_bucket && vm_projected_load < best_existing_load)) {
            best_existing_bucket = bucket;
            best_existing_load = vm_projected_load;
            best_existing_vm = vm_id;
        }
    }

    MachineId_t best_machine = numeric_limits<MachineId_t>::max();
    int best_machine_bucket = numeric_limits<int>::max();
    double best_machine_load = numeric_limits<double>::max();

    for(MachineId_t machine_id : machines) {
        const MachineInfo_t & machine_info = machine_infos.at(machine_id);
        if(pending_state_changes.count(machine_id) != 0 ||
           machine_info.cpu != required_cpu ||
           machine_info.s_state != S0) {
            continue;
        }
        if(!has_machine_memory_for_task(machine_id, true)) {
            SimOutput("Scheduler::NewTask(): Skipping machine " + to_string(machine_id) +
                      " for task " + to_string(task_id) + " due to memory pressure", 3);
            continue;
        }

        double machine_projected_load = projected_load(machine_id, true);
        int bucket = placement_bucket_for_machine(machine_id);
        if(machine_projected_load <= kOverloadThreshold) {
            bucket = max(0, bucket - 1);
        }

        if(bucket < best_machine_bucket ||
           (bucket == best_machine_bucket && machine_projected_load < best_machine_load)) {
            best_machine_bucket = bucket;
            best_machine_load = machine_projected_load;
            best_machine = machine_id;
        }
    }

    bool use_existing_vm = false;
    if(best_existing_vm != numeric_limits<VMId_t>::max()) {
        use_existing_vm = true;
        if(best_machine != numeric_limits<MachineId_t>::max()) {
            bool new_machine_is_better =
                (best_machine_bucket < best_existing_bucket) ||
                (best_machine_bucket == best_existing_bucket &&
                 best_machine_load < best_existing_load) ||
                (best_machine_bucket == best_existing_bucket &&
                 best_machine_load == best_existing_load &&
                 RequiredSLA(task_id) == SLA0);
            if(new_machine_is_better) {
                use_existing_vm = false;
            }
        }
    }

    if(use_existing_vm) {
        VMInfo_t vm_info = VM_GetInfo(best_existing_vm);
        MachineInfo_t machine_info = Machine_GetInfo(vm_info.machine_id);
        if(pending_state_changes.count(vm_info.machine_id) != 0 ||
           machine_info.s_state != S0) {
            SimOutput("Scheduler::NewTask(): existing VM " + to_string(best_existing_vm) +
                      " became unavailable before placement on machine " +
                      to_string(vm_info.machine_id), 1);
            use_existing_vm = false;
        }
    }

    if(use_existing_vm) {
        VMInfo_t vm_info = VM_GetInfo(best_existing_vm);
        idle_since.erase(vm_info.machine_id);
        VM_AddTask(best_existing_vm, task_id, priority);
        task_to_vm[task_id] = best_existing_vm;
        SimOutput("Scheduler::NewTask(): Added task " + to_string(task_id) +
                  " to existing VM " + to_string(best_existing_vm) +
                  " bucket=" + to_string(best_existing_bucket) +
                  " projected_load=" + to_string(best_existing_load), 2);
        return true;
    }

    if(best_machine != numeric_limits<MachineId_t>::max()) {
        MachineInfo_t latest_machine_info = Machine_GetInfo(best_machine);
        if(pending_state_changes.count(best_machine) != 0 ||
           latest_machine_info.s_state != S0) {
            SimOutput("Scheduler::NewTask(): machine " + to_string(best_machine) +
                      " became unavailable before VM attach for task " +
                      to_string(task_id), 1);
            return false;
        }
        idle_since.erase(best_machine);
        VMId_t vm_id = VM_Create(RequiredVMType(task_id), RequiredCPUType(task_id));
        VM_Attach(vm_id, best_machine);
        vms.push_back(vm_id);
        vm_slas[vm_id] = RequiredSLA(task_id);
        machine_sla_vm_counts[best_machine][RequiredSLA(task_id)]++;
        VM_AddTask(vm_id, task_id, priority);
        task_to_vm[task_id] = vm_id;
        SimOutput("Scheduler::NewTask(): Created VM " + to_string(vm_id) +
                  " on machine " + to_string(best_machine) +
                  " for task " + to_string(task_id) +
                  " bucket=" + to_string(best_machine_bucket) +
                  " projected_load=" + to_string(best_machine_load), 1);
        return true;
    }

    if(log_failure) {
        TaskInfo_t task_info = GetTaskInfo(task_id);
        SimOutput("Scheduler::NewTask(): failed to place task " + to_string(task_id) +
                  " cpu=" + to_string(task_info.required_cpu) +
                  " vm=" + to_string(task_info.required_vm) +
                  " mem=" + to_string(task_info.required_memory), 2);
        for(MachineId_t machine_id : machines) {
            MachineInfo_t machine_info = Machine_GetInfo(machine_id);
            string reason;
            if(machine_info.cpu != RequiredCPUType(task_id)) {
                reason = "cpu_mismatch";
            } else if(!IsMachineReady(machine_id)) {
                reason = "not_ready_state=" + to_string(machine_info.s_state);
            } else if(!HasMachineMemoryForTask(machine_id, task_id, true)) {
                reason = "no_memory used=" + to_string(machine_info.memory_used) +
                         " size=" + to_string(machine_info.memory_size);
            } else if(host_states[machine_id] == HostState::OVERLOADED) {
                reason = "classified_overloaded";
            } else if(ProjectedLoad(machine_id, task_id, true) > kOverloadThreshold) {
                reason = "overload_threshold projected=" +
                         to_string(ProjectedLoad(machine_id, task_id, true));
            } else {
                reason = "candidate_unused";
            }

            SimOutput("Scheduler::NewTask(): machine " + to_string(machine_id) +
                      " reason=" + reason +
                      " active_tasks=" + to_string(machine_info.active_tasks) +
                      " active_vms=" + to_string(machine_info.active_vms), 3);
        }
    }

    return false;
}

bool Scheduler::TryWakeMachineForTask(TaskId_t task_id) {
    MachineId_t best_machine = numeric_limits<MachineId_t>::max();
    double best_machine_load = numeric_limits<double>::max();

    for(MachineId_t machine_id : machines) {
        if(pending_state_changes.count(machine_id) != 0) {
            continue;
        }

        MachineInfo_t machine_info = Machine_GetInfo(machine_id);
        if(machine_info.cpu != RequiredCPUType(task_id) || machine_info.s_state == S0) {
            continue;
        }
        if(!HasMachineMemoryForTask(machine_id, task_id, true)) {
            continue;
        }

        double projected_load = ProjectedLoad(machine_id, task_id, true);
        if(projected_load < best_machine_load) {
            best_machine_load = projected_load;
            best_machine = machine_id;
        }
    }

    if(best_machine == numeric_limits<MachineId_t>::max()) {
        return false;
    }

    idle_since.erase(best_machine);
    low_power_since.erase(best_machine);
    pending_state_changes.insert(best_machine);
    Machine_SetState(best_machine, S0);
    SimOutput("Scheduler::TryWakeMachineForTask(): waking machine " +
              to_string(best_machine) + " for task " + to_string(task_id), 1);
    return true;
}

unsigned Scheduler::CountReadyMachines(CPUType_t cpu_type, MachineId_t exclude_machine) const {
    unsigned ready_count = 0;
    for(MachineId_t candidate : machines) {
        if(candidate == exclude_machine) {
            continue;
        }
        if(pending_state_changes.count(candidate) != 0) {
            continue;
        }

        MachineInfo_t machine_info = Machine_GetInfo(candidate);
        if(machine_info.cpu == cpu_type && machine_info.s_state == S0) {
            ready_count++;
        }
    }
    return ready_count;
}

unsigned Scheduler::CountReadyPreferredMachines(CPUType_t cpu_type, MachineId_t exclude_machine) const {
    unsigned ready_count = 0;
    for(MachineId_t candidate : machines) {
        if(candidate == exclude_machine) {
            continue;
        }
        if(pending_state_changes.count(candidate) != 0) {
            continue;
        }

        MachineInfo_t machine_info = Machine_GetInfo(candidate);
        if(machine_info.cpu == cpu_type &&
           machine_info.s_state == S0 &&
           IsPreferredMachineForCpu(best_capacity_by_cpu, machine_info)) {
            ready_count++;
        }
    }
    return ready_count;
}

unsigned Scheduler::CountReadyGpuMachines(CPUType_t cpu_type, MachineId_t exclude_machine) const {
    unsigned ready_count = 0;
    for(MachineId_t candidate : machines) {
        if(candidate == exclude_machine) {
            continue;
        }
        if(pending_state_changes.count(candidate) != 0) {
            continue;
        }

        MachineInfo_t machine_info = Machine_GetInfo(candidate);
        if(machine_info.cpu == cpu_type &&
           machine_info.s_state == S0 &&
           machine_info.gpus) {
            ready_count++;
        }
    }
    return ready_count;
}

void Scheduler::MaybeSleepMachine(MachineId_t machine_id, Time_t now) {
    if(!kEnableIdleSleep) {
        return;
    }
    if(!waiting_tasks.empty()) {
        idle_since.erase(machine_id);
        return;
    }
    if(pending_state_changes.count(machine_id) != 0) {
        idle_since.erase(machine_id);
        return;
    }
    if(IsMachineProtected(machine_id, now)) {
        idle_since.erase(machine_id);
        return;
    }
    MachineInfo_t machine_info = Machine_GetInfo(machine_id);
    bool is_preferred = IsPreferredMachineForCpu(best_capacity_by_cpu, machine_info);
    if(machine_info.active_tasks != 0 || machine_info.active_vms != 0) {
        idle_since.erase(machine_id);
        low_power_since.erase(machine_id);
        return;
    }

    if(machine_info.s_state == S0i1) {
        idle_since.erase(machine_id);
        if(is_preferred || machine_info.gpus) {
            return;
        }

        auto low_power_it = low_power_since.find(machine_id);
        if(low_power_it == low_power_since.end()) {
            low_power_since[machine_id] = now;
            return;
        }
        if(now - low_power_it->second < kColdShutdownDelay) {
            return;
        }

        low_power_since.erase(machine_id);
        pending_state_changes.insert(machine_id);
        Machine_SetState(machine_id, S5);
        SimOutput("Scheduler::MaybeSleepMachine(): moving cold idle machine " +
                  to_string(machine_id) + " from S0i1 to S5 at time " +
                  to_string(now), 1);
        return;
    }

    if(machine_info.s_state != S0) {
        idle_since.erase(machine_id);
        low_power_since.erase(machine_id);
        return;
    }

    if(machine_info.gpus &&
       CountReadyGpuMachines(machine_info.cpu, machine_id) < kMinReadyGpuMachinesPerCpu) {
        return;
    }

    if(is_preferred) {
        if(CountReadyPreferredMachines(machine_info.cpu, machine_id) < kMinReadyPreferredMachinesPerCpu) {
            return;
        }
    } else if(CountReadyMachines(machine_info.cpu, machine_id) < kMinReadyMachinesPerCpu) {
        return;
    }

    auto idle_it = idle_since.find(machine_id);
    if(idle_it == idle_since.end()) {
        idle_since[machine_id] = now;
        return;
    }
    Time_t idle_delay = is_preferred ? kPreferredIdleSleepDelay : kIdleSleepDelay;
    if(now - idle_it->second < idle_delay) {
        return;
    }

    idle_since.erase(machine_id);
    low_power_since[machine_id] = now;
    pending_state_changes.insert(machine_id);
    Machine_SetState(machine_id, S0i1);
    SimOutput("Scheduler::MaybeSleepMachine(): moving idle machine " +
              to_string(machine_id) + " to S0i1 at time " + to_string(now), 1);
}

void Scheduler::ProtectMachine(MachineId_t machine_id, Time_t now) {
    Time_t until = now + kProtectionWindow;
    auto it = protected_until.find(machine_id);
    if(it == protected_until.end() || it->second < until) {
        protected_until[machine_id] = until;
    }
}

bool Scheduler::IsMachineProtected(MachineId_t machine_id, Time_t now) const {
    auto it = protected_until.find(machine_id);
    return it != protected_until.end() && it->second > now;
}

void Scheduler::RetryWaitingTasks(Time_t now) {
    if(waiting_tasks.empty()) {
        return;
    }

    vector<TaskId_t> pending_tasks;
    pending_tasks.swap(waiting_tasks);
    for(TaskId_t task_id : pending_tasks) {
        if(IsTaskCompleted(task_id)) {
            continue;
        }
        if(TryPlaceTask(task_id, false)) {
            SimOutput("Scheduler::RetryWaitingTasks(): placed waiting task " +
                      to_string(task_id) + " at time " + to_string(now), 2);
        } else {
            waiting_tasks.push_back(task_id);
        }
    }
}

void Scheduler::Init() {
    unsigned total_machines = Machine_GetTotal();
    total_tasks = GetNumTasks();
    completed_tasks = 0;
    next_progress_percent = 10;
    SimOutput("Scheduler::Init(): Total number of machines is " + to_string(total_machines), 3);
    SimOutput("Scheduler::Init(): Total number of tasks is " + to_string(total_tasks), 2);
    SimOutput("Scheduler::Init(): Initializing scheduler", 1);
    for(unsigned i = 0; i < total_machines; i++) {
        machines.push_back(MachineId_t(i));
        MachineInfo_t info = Machine_GetInfo(MachineId_t(i));
        uint64_t machine_capacity = MachineCapacityScore(MachineId_t(i));
        auto it = best_capacity_by_cpu.find(info.cpu);
        if(it == best_capacity_by_cpu.end() || it->second < machine_capacity) {
            best_capacity_by_cpu[info.cpu] = machine_capacity;
        }
        machine_sla_vm_counts[MachineId_t(i)].fill(0);
        SimOutput("Scheduler::Init(): machine " + to_string(i) +
                  " cpu=" + to_string(info.cpu) +
                  " mem=" + to_string(info.memory_size) +
                  " cpus=" + to_string(info.num_cpus) +
                  " gpu=" + string(info.gpus ? "yes" : "no"), 2);
    }
}

void Scheduler::MigrationComplete(Time_t time, VMId_t vm_id) {
    (void)time;
    (void)vm_id;
}

void Scheduler::NewTask(Time_t now, TaskId_t task_id) {
    if(!TryPlaceTask(task_id, true)) {
        TryWakeMachineForTask(task_id);
        waiting_tasks.push_back(task_id);
        SimOutput("Scheduler::NewTask(): queued task " + to_string(task_id) +
                  " at time " + to_string(now) + " waiting_count=" +
                  to_string(waiting_tasks.size()), 1);
    }
}

void Scheduler::PeriodicCheck(Time_t now) {
    RefreshMachineStates();
    for(MachineId_t machine_id : machines) {
        MaybeSleepMachine(machine_id, now);
    }
    RetryWaitingTasks(now);
}

void Scheduler::Shutdown(Time_t time) {
    for(auto & vm: vms) {
        VM_Shutdown(vm);
    }
}

void Scheduler::TaskComplete(Time_t now, TaskId_t task_id) {
    if(completed_tasks < total_tasks) {
        completed_tasks++;
    }
    if(total_tasks > 0) {
        unsigned progress_percent = (completed_tasks * 100) / total_tasks;
        while(next_progress_percent <= 100 && progress_percent >= next_progress_percent) {
            SimOutput("Scheduler::Progress(): " + to_string(next_progress_percent) +
                      "% complete (" + to_string(completed_tasks) + "/" +
                      to_string(total_tasks) + " tasks) at time " + to_string(now), 0);
            next_progress_percent += 10;
        }
    }

    auto vm_it = task_to_vm.find(task_id);
    if(vm_it != task_to_vm.end()) {
        VMId_t vm_id = vm_it->second;
        task_to_vm.erase(vm_it);

        if(find(vms.begin(), vms.end(), vm_id) == vms.end()) {
            RetryWaitingTasks(now);
            SimOutput("Scheduler::TaskComplete(): Task " + to_string(task_id) +
                      " completed after VM " + to_string(vm_id) +
                      " was already retired", 2);
            return;
        }

        VMInfo_t vm_info = VM_GetInfo(vm_id);
        if(vm_info.active_tasks.empty()) {
            for(auto it = task_to_vm.begin(); it != task_to_vm.end(); ) {
                if(it->second == vm_id) {
                    it = task_to_vm.erase(it);
                } else {
                    ++it;
                }
            }
            auto vm_sla_it = vm_slas.find(vm_id);
            if(vm_sla_it != vm_slas.end()) {
                auto machine_counts_it = machine_sla_vm_counts.find(vm_info.machine_id);
                if(machine_counts_it != machine_sla_vm_counts.end() &&
                   machine_counts_it->second[vm_sla_it->second] > 0) {
                    machine_counts_it->second[vm_sla_it->second]--;
                }
            }
            VM_Shutdown(vm_id);
            vms.erase(remove(vms.begin(), vms.end(), vm_id), vms.end());
            vm_slas.erase(vm_id);
        }
    }

    RetryWaitingTasks(now);
}

void Scheduler::StateChangeFinished(Time_t time, MachineId_t machine_id) {
    pending_state_changes.erase(machine_id);
    MachineInfo_t machine_info = Machine_GetInfo(machine_id);
    if(machine_info.s_state == S0) {
        low_power_since.erase(machine_id);
    } else if(machine_info.s_state == S0i1 || machine_info.s_state == S5) {
        low_power_since[machine_id] = time;
    }
    SimOutput("Scheduler::StateChangeFinished(): machine " + to_string(machine_id) +
              " completed state change at time " + to_string(time), 2);
    RetryWaitingTasks(time);
}

void Scheduler::HandleSLAWarning(Time_t time, TaskId_t task_id) {
    SetTaskPriority(task_id, HIGH_PRIORITY);

    auto vm_it = task_to_vm.find(task_id);
    if(vm_it == task_to_vm.end()) {
        SimOutput("Scheduler::HandleSLAWarning(): raised priority for task " +
                  to_string(task_id) + " at time " + to_string(time), 1);
        return;
    }

    VMInfo_t vm_info = VM_GetInfo(vm_it->second);
    ProtectMachine(vm_info.machine_id, time);
    SimOutput("Scheduler::HandleSLAWarning(): task " + to_string(task_id) +
              " warned at time " + to_string(time) +
              ", raised to HIGH priority and protected machine " +
              to_string(vm_info.machine_id), 1);

    TryWakeMachineForTask(task_id);
}

void Scheduler::HandleMemoryWarning(Time_t time, MachineId_t machine_id) {
    ProtectMachine(machine_id, time);
    SimOutput("MemoryWarning(): Overflow at " + to_string(machine_id) +
              " was detected at time " + to_string(time), 0);
}

static Scheduler Scheduler;

void InitScheduler() {
    Scheduler.Init();
}

void HandleNewTask(Time_t time, TaskId_t task_id) {
    Scheduler.NewTask(time, task_id);
}

void HandleTaskCompletion(Time_t time, TaskId_t task_id) {
    Scheduler.TaskComplete(time, task_id);
}

void MemoryWarning(Time_t time, MachineId_t machine_id) {
    Scheduler.HandleMemoryWarning(time, machine_id);
}

void MigrationDone(Time_t time, VMId_t vm_id) {
    Scheduler.MigrationComplete(time, vm_id);
}

void SchedulerCheck(Time_t time) {
    Scheduler.PeriodicCheck(time);
}

void SimulationComplete(Time_t time) {
    cout << "SLA violation report" << endl;
    cout << "SLA0: " << GetSLAReport(SLA0) << "%" << endl;
    cout << "SLA1: " << GetSLAReport(SLA1) << "%" << endl;
    cout << "SLA2: " << GetSLAReport(SLA2) << "%" << endl;
    cout << "Total Energy " << Machine_GetClusterEnergy() << "KW-Hour" << endl;
    cout << "Simulation run finished in " << double(time)/1000000 << " seconds" << endl;
    Scheduler.Shutdown(time);
}

void SLAWarning(Time_t time, TaskId_t task_id) {
    Scheduler.HandleSLAWarning(time, task_id);
}

void StateChangeComplete(Time_t time, MachineId_t machine_id) {
    Scheduler.StateChangeFinished(time, machine_id);
}
