// Much of this code was generated by an LLM, but designed
// in parallel by the user. The user is responsible for the final content and 
// any errors in the code.
//
//  Scheduler.cpp
//  CloudSim
//
//  Created by ELMOOTAZBELLAH ELNOZAHY on 10/20/24.
//

#include "Scheduler.hpp"

#include <algorithm>
#include <cmath>
#include <limits>

// =============================================================================
// SECTION 1 — Machine view initialisation
// =============================================================================

void Scheduler::InitializeMachineViews() {
    machines.clear();
    machine_views.clear();

    const unsigned total = Machine_GetTotal();
    for(unsigned i = 0; i < total; i++) {
        const MachineId_t   machine_id = MachineId_t(i);
        const MachineInfo_t info       = Machine_GetInfo(machine_id);

        machines.push_back(machine_id);
        machine_views[machine_id] = MachineStateView{
            machine_id,
            info.cpu,
            info.num_cpus,
            info.performance[P0],
            info.memory_size,
            info.memory_used,
            info.gpus,
            info.s_state,
            info.active_tasks,
            false,          // state_change_pending
            info.s_state    // target_state — no pending transition at init
        };
    }

    // Build sorted_machines: fastest (highest mips_p0) first.
    sorted_machines = machines;
    sort(sorted_machines.begin(), sorted_machines.end(),
         [this](MachineId_t a, MachineId_t b) {
             return machine_views[a].mips_p0 > machine_views[b].mips_p0;
         });
}

void Scheduler::ClassifyMachinesIntoTiers() {
    const unsigned total = static_cast<unsigned>(machines.size());
    if(total == 0) return;

    for(unsigned i = 0; i < total; i++) {
        const MachineId_t machine_id = sorted_machines[i];
        auto &view = machine_views[machine_id];
        machine_tier[machine_id] = MachineTier::Running;
        if(view.s_state != S0) {
            Machine_SetState(machine_id, S0);
            view.state_change_pending = true;
            view.target_state         = S0;
        }
    }
    SimOutput("ClassifyMachinesIntoTiers(): all " + to_string(total)
              + " machines targeted S0; E-Eco will demote idle ones over time", 2);
}

// =============================================================================
// SECTION 2 — Shadow state sync
// =============================================================================

// FIX: Only refreshes s_state from the simulator.
//
// tracked_memory_used and active_task_count are intentionally NOT overwritten.
// Those fields are maintained by TryPlaceTask (increments) and TaskComplete
// (decrements) and are always more accurate than the simulator's view during
// burst absorption.  The simulator lags behind in-flight VM_AddTask calls.
//
// Overwriting load accounting here caused the "CPU already in C0" crash: when
// PeriodicCheck and StateChangeComplete fire at the same timestamp, the refresh
// reset machines to zero load after ProcessRetryQueue had already placed tasks
// on them, causing AdjustTiers → ProcessRetryQueue to place a second full
// batch on the same machines, overrunning their CPUs.
//
// s_state IS refreshed because power-state transitions (S0/S1/S5) are not
// tracked by placement or completion logic and must be read from the simulator.
void Scheduler::RefreshMachineStatesFromSimulator() {
    for(const auto machine_id : machines) {
        const MachineInfo_t info = Machine_GetInfo(machine_id);
        machine_views[machine_id].s_state = info.s_state;
    }
}


// =============================================================================
// SECTION 3 — Placement helpers
// =============================================================================

Priority_t Scheduler::PriorityFromSLA(SLAType_t sla) const {
    switch(sla) {
        case SLA0:  return HIGH_PRIORITY;
        case SLA1:  return MID_PRIORITY;
        case SLA2:  return LOW_PRIORITY;
        case SLA3:
        default:    return LOW_PRIORITY;
    }
}

double Scheduler::MaxLoadForSLA(SLAType_t sla) const {
    // switch(sla) {
    //     case SLA0:  return kLoadCapSLA0;
    //     case SLA1:  return kLoadCapSLA1;
    //     case SLA2:  return kLoadCapSLA2;
    //     case SLA3:
    //     default:    return kLoadCapSLA3;
    // }
    return 1.0;
}

unsigned Scheduler::AdditionalPlacementMemory(TaskId_t task_id, bool creating_vm) const {
    const auto it = task_states.find(task_id);
    if(it == task_states.end()) return 0;
    unsigned extra = it->second.required_memory;
    if(creating_vm) extra += VM_MEMORY_OVERHEAD;
    return extra;
}

bool Scheduler::IsHardwareCompatible(TaskId_t task_id) const {
    const auto task_it = task_states.find(task_id);
    if(task_it == task_states.end()) return false;
    const TaskState &task = task_it->second;

    for(const auto machine_id : machines) {
        const auto &machine = machine_views.at(machine_id);
        if(machine.cpu != task.required_cpu) continue;
        if(task.gpu_capable && !machine.gpu_enabled) continue;
        return true;
    }
    return false;
}

// Feasibility enforces tier membership implicitly: only Running-tier machines
// have s_state == S0 with state_change_pending == false.
bool Scheduler::IsMachineFeasible(TaskId_t task_id, MachineId_t machine_id,
                                   bool creating_vm) const {
    const auto machine_it = machine_views.find(machine_id);
    if(machine_it == machine_views.end()) return false;
    const auto task_it = task_states.find(task_id);
    if(task_it == task_states.end()) return false;

    const MachineStateView &machine = machine_it->second;
    const TaskState        &task    = task_it->second;

    if(machine.s_state != S0)                    return false;
    if(machine.state_change_pending)             return false;
    if(machine.cpu != task.required_cpu)         return false;
    if(task.gpu_capable && !machine.gpu_enabled) return false;
    if(machine.memory_capacity == 0)             return false;

    const unsigned projected_mem = machine.tracked_memory_used
                                 + AdditionalPlacementMemory(task_id, creating_vm);
    if(projected_mem >= machine.memory_capacity) return false;

    if(machine.num_cores == 0) return false;
    const double projected_load = static_cast<double>(machine.active_task_count + 1)
                                / static_cast<double>(machine.num_cores);
    return projected_load <= MaxLoadForSLA(task.required_sla);
}

bool Scheduler::HasReusableVM(MachineId_t machine_id, VMType_t vm_type,
                               CPUType_t cpu, VMId_t &out_vm_id) const {
    out_vm_id = VMId_t(-1);
    const auto it = machine_to_vms.find(machine_id);
    if(it == machine_to_vms.end()) return false;

    for(const VMId_t id : it->second) {
        const auto vm_it = vm_states.find(id);
        if(vm_it == vm_states.end()) continue;
        const VMState &vm = vm_it->second;
        if(vm.vm_type == vm_type && vm.cpu == cpu) {
            out_vm_id = id;
            return true;
        }
    }
    return false;
}


// =============================================================================
// SECTION 4 — E-Eco tier controller
// =============================================================================

unsigned Scheduler::ComputeDesiredRunning() const {
    unsigned total_active  = 0;
    unsigned total_cores   = 0;
    unsigned running_count = 0;

    for(const auto machine_id : machines) {
        const auto tier_it = machine_tier.find(machine_id);
        if(tier_it == machine_tier.end()) continue;
        if(tier_it->second != MachineTier::Running) continue;

        const auto view_it = machine_views.find(machine_id);
        if(view_it == machine_views.end()) continue;

        total_active  += view_it->second.active_task_count;
        total_cores   += view_it->second.num_cores;
        running_count++;
    }

    if(running_count == 0) return kMinRunningMachines;

    const unsigned avg_cores = max(1u, total_cores / running_count);
    const double capacity_per_machine =
        kTargetLoadPerMachine * static_cast<double>(avg_cores);

    if(capacity_per_machine <= 0.0) return kMinRunningMachines;

    const unsigned desired = static_cast<unsigned>(
        ceil(static_cast<double>(total_active) / capacity_per_machine));

    return max(kMinRunningMachines, desired);
}

unsigned Scheduler::ComputeDesiredIntermediate(unsigned running_count) const {
    const unsigned desired = static_cast<unsigned>(
        ceil(static_cast<double>(running_count) * kIntermediateBufferRatio));
    return max(kMinIntermediateMachines, desired);
}

// Core E-Eco tier controller.  Called from PeriodicCheck after simulator sync.
//
// Step 1 — Compute desired Running from current active task load.
// Step 2 — Apply queue-aware promotion bias for SLA0/SLA1 queued tasks.
// Step 3 — Promote Intermediate → Running if undersized (fast machines first).
// Step 4 — Demote idle Running → Intermediate if oversized (slow machines first).
// Step 5 — Balance Intermediate ↔ SwitchedOff.
void Scheduler::AdjustTiers(Time_t now) {
    (void)now;

    // -- Count current tier occupancy ------------------------------------------
    unsigned current_running      = 0;
    unsigned current_intermediate = 0;

    for(const auto machine_id : machines) {
        const auto it = machine_tier.find(machine_id);
        if(it == machine_tier.end()) continue;
        switch(it->second) {
            case MachineTier::Running:      current_running++;      break;
            case MachineTier::Intermediate: current_intermediate++; break;
            default: break;
        }
    }

    // -- Step 1: steady-state desired ------------------------------------------
    unsigned desired_running = ComputeDesiredRunning();

    // -- Step 2: queue-aware promotion bias ------------------------------------
    if(queued_sla0_count > 0) {
        const unsigned sla0_bias =
            max(1u, (queued_sla0_count + kQueueBiasTasksPerMachine - 1)
                    / kQueueBiasTasksPerMachine);
        desired_running += sla0_bias;
        SimOutput("AdjustTiers(): SLA0 queue bias +" + to_string(sla0_bias)
                  + " (queued=" + to_string(queued_sla0_count) + ")", 3);
    }
    if(queued_sla1_count > 0) {
        const unsigned sla1_bias =
            max(1u, (queued_sla1_count + kQueueBiasTasksPerMachine * 2 - 1)
                    / (kQueueBiasTasksPerMachine * 2));
        desired_running += sla1_bias;
        SimOutput("AdjustTiers(): SLA1 queue bias +" + to_string(sla1_bias)
                  + " (queued=" + to_string(queued_sla1_count) + ")", 3);
    }

    desired_running = min(desired_running,
                          static_cast<unsigned>(machines.size()));

    const unsigned desired_intermediate = ComputeDesiredIntermediate(desired_running);

    // -- Step 3: promote Intermediate → Running --------------------------------
    if(current_running < desired_running) {
        for(const auto machine_id : sorted_machines) {
            if(current_running >= desired_running) break;

            const auto tier_it = machine_tier.find(machine_id);
            if(tier_it == machine_tier.end()) continue;
            if(tier_it->second != MachineTier::Intermediate) continue;

            auto &view = machine_views[machine_id];
            if(view.state_change_pending) continue;

            Machine_SetState(machine_id, S0);
            view.state_change_pending = true;
            view.target_state         = S0;
            machine_tier[machine_id]  = MachineTier::Running;
            current_running++;
            tier_promotions++;
            SimOutput("AdjustTiers(): promoted machine " + to_string(machine_id)
                      + " Intermediate→Running", 2);
        }

        // Intermediate exhausted — escalate from SwitchedOff.
        if(current_running < desired_running) {
            for(const auto machine_id : sorted_machines) {
                if(current_running >= desired_running) break;

                const auto tier_it = machine_tier.find(machine_id);
                if(tier_it == machine_tier.end()) continue;
                if(tier_it->second != MachineTier::SwitchedOff) continue;

                auto &view = machine_views[machine_id];
                if(view.state_change_pending) continue;

                Machine_SetState(machine_id, S0);
                view.state_change_pending = true;
                view.target_state         = S0;
                machine_tier[machine_id]  = MachineTier::Running;
                current_running++;
                tier_promotions++;
                SimOutput("AdjustTiers(): escalated machine " + to_string(machine_id)
                          + " SwitchedOff→Running", 2);
            }
        }
    }

    // -- Step 4: demote idle Running → Intermediate ----------------------------
    if(current_running > desired_running) {
        for(int i = static_cast<int>(sorted_machines.size()) - 1; i >= 0; i--) {
            if(current_running <= desired_running) break;

            const MachineId_t machine_id = sorted_machines[i];
            const auto tier_it = machine_tier.find(machine_id);
            if(tier_it == machine_tier.end()) continue;
            if(tier_it->second != MachineTier::Running) continue;

            auto &view = machine_views[machine_id];
            if(view.active_task_count > 0) continue;
            if(view.state_change_pending)  continue;

            Machine_SetState(machine_id, S1);
            view.state_change_pending = true;
            view.target_state         = S1;
            machine_tier[machine_id]  = MachineTier::Intermediate;
            current_running--;
            current_intermediate++;
            tier_demotions++;
            SimOutput("AdjustTiers(): demoted machine " + to_string(machine_id)
                      + " Running→Intermediate", 2);
        }
    }

    // -- Step 5: balance Intermediate ↔ SwitchedOff ---------------------------

    if(current_intermediate < desired_intermediate) {
        for(const auto machine_id : sorted_machines) {
            if(current_intermediate >= desired_intermediate) break;

            const auto tier_it = machine_tier.find(machine_id);
            if(tier_it == machine_tier.end()) continue;
            if(tier_it->second != MachineTier::SwitchedOff) continue;

            auto &view = machine_views[machine_id];
            if(view.state_change_pending) continue;

            Machine_SetState(machine_id, S1);
            view.state_change_pending = true;
            view.target_state         = S1;
            machine_tier[machine_id]  = MachineTier::Intermediate;
            current_intermediate++;
            SimOutput("AdjustTiers(): warmed machine " + to_string(machine_id)
                      + " SwitchedOff→Intermediate", 3);
        }
    }

    if(current_intermediate > desired_intermediate) {
        for(int i = static_cast<int>(sorted_machines.size()) - 1; i >= 0; i--) {
            if(current_intermediate <= desired_intermediate) break;

            const MachineId_t machine_id = sorted_machines[i];
            const auto tier_it = machine_tier.find(machine_id);
            if(tier_it == machine_tier.end()) continue;
            if(tier_it->second != MachineTier::Intermediate) continue;

            auto &view = machine_views[machine_id];
            if(view.active_task_count > 0) continue;
            if(view.state_change_pending)  continue;

            Machine_SetState(machine_id, S5);
            view.state_change_pending = true;
            view.target_state         = S5;
            machine_tier[machine_id]  = MachineTier::SwitchedOff;
            current_intermediate--;
            SimOutput("AdjustTiers(): cooled machine " + to_string(machine_id)
                      + " Intermediate→SwitchedOff", 3);
        }
    }
}

// Immediate reactive promotion for SLA0/SLA1 task placement failures.
// Fires on the same event tick as the failing NewTask, rather than waiting
// for the next PeriodicCheck.  SLA2/SLA3 rely on AdjustTiers' queue-aware bias.
void Scheduler::PromoteForTask(TaskId_t task_id) {
    const auto task_it = task_states.find(task_id);
    if(task_it == task_states.end()) return;

    const TaskState &task = task_it->second;
    if(task.required_sla != SLA0 && task.required_sla != SLA1) return;

    // Try Intermediate first (fast wake from S1).
    for(const auto machine_id : sorted_machines) {
        const auto tier_it = machine_tier.find(machine_id);
        if(tier_it == machine_tier.end()) continue;
        if(tier_it->second != MachineTier::Intermediate) continue;

        auto &view = machine_views[machine_id];
        if(view.state_change_pending)             continue;
        if(view.cpu != task.required_cpu)         continue;
        if(task.gpu_capable && !view.gpu_enabled) continue;

        Machine_SetState(machine_id, S0);
        view.state_change_pending = true;
        view.target_state         = S0;
        machine_tier[machine_id]  = MachineTier::Running;
        tier_promotions++;
        SimOutput("PromoteForTask(): Intermediate→Running machine "
                  + to_string(machine_id) + " for SLA"
                  + to_string(static_cast<int>(task.required_sla))
                  + " task " + to_string(task_id), 2);
        return;
    }

    // Intermediate exhausted — escalate from SwitchedOff.
    for(const auto machine_id : sorted_machines) {
        const auto tier_it = machine_tier.find(machine_id);
        if(tier_it == machine_tier.end()) continue;
        if(tier_it->second != MachineTier::SwitchedOff) continue;

        auto &view = machine_views[machine_id];
        if(view.state_change_pending)             continue;
        if(view.cpu != task.required_cpu)         continue;
        if(task.gpu_capable && !view.gpu_enabled) continue;

        Machine_SetState(machine_id, S0);
        view.state_change_pending = true;
        view.target_state         = S0;
        machine_tier[machine_id]  = MachineTier::Running;
        tier_promotions++;
        SimOutput("PromoteForTask(): SwitchedOff→Running machine "
                  + to_string(machine_id) + " (Intermediate exhausted) for SLA"
                  + to_string(static_cast<int>(task.required_sla))
                  + " task " + to_string(task_id), 1);
        return;
    }
}


// =============================================================================
// SECTION 5 — Placement and retry queue
// =============================================================================

// SLA0/SLA1 → fast→slow (fastest available machine).
// SLA2/SLA3 → slow→fast (leave fast machines free for SLA0/SLA1).
// Shadow state updated synchronously — no simulator refresh here.
bool Scheduler::TryPlaceTask(TaskId_t task_id) {
    const auto task_it = task_states.find(task_id);
    if(task_it == task_states.end()) return false;

    TaskState &task = task_it->second;
    if(task.placement_failed || task.assigned || task.completed) return false;

    const CPUType_t  required_cpu = task.required_cpu;
    const VMType_t   required_vm  = task.required_vm;
    const Priority_t priority     = task.assigned_priority;
    const SLAType_t  required_sla = task.required_sla;

    const bool prefer_fast = (required_sla == SLA0 || required_sla == SLA1);
    const int  n           = static_cast<int>(sorted_machines.size());

    for(int idx = 0; idx < n; idx++) {
        const int         i          = prefer_fast ? idx : (n - 1 - idx);
        const MachineId_t machine_id = sorted_machines[i];

        VMId_t     vm_id       = VMId_t(-1);
        const bool has_reuse   = HasReusableVM(machine_id, required_vm, required_cpu, vm_id);
        const bool creating_vm = !has_reuse;

        if(!IsMachineFeasible(task_id, machine_id, creating_vm)) continue;

        if(creating_vm) {
            vm_id = VM_Create(required_vm, required_cpu);
            VM_Attach(vm_id, machine_id);
            vm_states[vm_id] = VMState{
                vm_id, machine_id, required_vm, required_cpu, VM_MEMORY_OVERHEAD
            };
            machine_to_vms[machine_id].push_back(vm_id);
            machine_views[machine_id].tracked_memory_used += VM_MEMORY_OVERHEAD;
            vms_created++;
        }

        VM_AddTask(vm_id, task_id, priority);
        vm_states[vm_id].tracked_memory_footprint     += task.required_memory;
        machine_views[machine_id].tracked_memory_used  += task.required_memory;
        machine_views[machine_id].active_task_count++;
        task.assigned    = true;
        task.assigned_vm = vm_id;
        successful_placements++;
        return true;
    }

    if(!IsHardwareCompatible(task_id)) {
        task.placement_failed = true;
        failed_task_ids.push_back(task_id);
        placement_failures++;
        SimOutput("TryPlaceTask(): task " + to_string(task_id)
                  + " has no compatible hardware — permanently dropped", 0);
    }
    return false;
}

void Scheduler::EnqueueRetry(TaskId_t task_id) {
    const auto task_it = task_states.find(task_id);
    if(task_it != task_states.end()) {
        switch(task_it->second.required_sla) {
            case SLA0: queued_sla0_count++; break;
            case SLA1: queued_sla1_count++; break;
            default:   break;
        }
    }
    retry_queue.push_back({task_id});
    retry_enqueues++;
}

void Scheduler::DecrementQueuedSLACount(TaskId_t task_id) {
    const auto task_it = task_states.find(task_id);
    if(task_it == task_states.end()) return;
    switch(task_it->second.required_sla) {
        case SLA0: if(queued_sla0_count > 0) queued_sla0_count--; break;
        case SLA1: if(queued_sla1_count > 0) queued_sla1_count--; break;
        default:   break;
    }
}

// Processes up to kRetryBatchCap entries.  Tasks that permanently exit the
// queue (placed or hardware-incompatible) decrement the SLA counters.
// Capacity-constrained tasks are re-appended; their counter stays live.
void Scheduler::ProcessRetryQueue(Time_t now) {
    const size_t batch =
        min(retry_queue.size(), static_cast<size_t>(kRetryBatchCap));

    for(size_t i = 0; i < batch; i++) {
        const RetryEntry entry = retry_queue.front();
        retry_queue.pop_front();

        const auto task_it = task_states.find(entry.task_id);
        if(task_it == task_states.end()) continue;

        const TaskState &task = task_it->second;

        if(task.placement_failed || task.completed || task.assigned) {
            DecrementQueuedSLACount(entry.task_id);
            continue;
        }

        retry_attempts++;

        if(TryPlaceTask(entry.task_id)) {
            DecrementQueuedSLACount(entry.task_id);
            continue;
        }

        if(task_it->second.placement_failed) {
            DecrementQueuedSLACount(entry.task_id);
            continue;
        }

        task_it->second.retry_count++;
        if(task_it->second.retry_count == 50) {
            SimOutput("ProcessRetryQueue(): task " + to_string(entry.task_id)
                      + " has missed 50 placements at time " + to_string(now)
                      + " — still retrying", 1);
        }
        retry_queue.push_back(entry);
    }
}


// =============================================================================
// SECTION 6 — Scheduler lifecycle
// =============================================================================

void Scheduler::Init() {
    const unsigned total = Machine_GetTotal();
    SimOutput("Scheduler::Init(): total machines = " + to_string(total), 3);
    SimOutput("Scheduler::Init(): initializing E-Eco scheduler", 1);

    task_states.clear();
    vm_states.clear();
    machine_to_vms.clear();
    machine_views.clear();
    machine_tier.clear();
    machines.clear();
    sorted_machines.clear();
    retry_queue.clear();
    failed_task_ids.clear();

    tasks_seen            = 0;
    tasks_completed       = 0;
    successful_placements = 0;
    retry_enqueues        = 0;
    retry_attempts        = 0;
    placement_failures    = 0;
    vms_created           = 0;
    tier_promotions       = 0;
    tier_demotions        = 0;
    queued_sla0_count     = 0;
    queued_sla1_count     = 0;

    InitializeMachineViews();
    ClassifyMachinesIntoTiers();
}

// StateChangeComplete fires here.  Checks whether the achieved state matches
// the commanded target before clearing state_change_pending.  If the machine
// is passing through an intermediate S-state (e.g. S2 on the way to S0),
// state_change_pending stays true so AdjustTiers does not re-issue a command.
void Scheduler::HandleMachineWake(Time_t time, MachineId_t machine_id) {
    auto machine_it = machine_views.find(machine_id);
    if(machine_it == machine_views.end()) return;

    MachineStateView &machine = machine_it->second;

    const MachineInfo_t info = Machine_GetInfo(machine_id);
    machine.s_state = info.s_state;

    if(info.s_state != machine.target_state) {
        SimOutput("HandleMachineWake(): machine " + to_string(machine_id)
                  + " still transitioning to S" + to_string(machine.target_state), 3);
        return;
    }

    machine.state_change_pending = false;
    // machine.tracked_memory_used  = info.memory_used;
    // machine.active_task_count    = info.active_tasks;

    if(info.s_state == S0) {
        machine_tier[machine_id] = MachineTier::Running;
        SimOutput("HandleMachineWake(): machine " + to_string(machine_id)
                  + " confirmed S0 at time " + to_string(time), 2);
        // NO ProcessRetryQueue here — PeriodicCheck drives all placement.
        // Draining the queue from HandleMachineWake caused concurrent
        // VM_AddTask bursts when multiple machines wake at the same timestamp.

    } else if(info.s_state == S1 || info.s_state == S2) {
        machine_tier[machine_id] = MachineTier::Intermediate;
        SimOutput("HandleMachineWake(): machine " + to_string(machine_id)
                  + " confirmed Intermediate at time " + to_string(time), 3);

    } else {
        machine_tier[machine_id] = MachineTier::SwitchedOff;
    }
}

void Scheduler::MigrationComplete(Time_t time, VMId_t vm_id) {
    (void)time;
    (void)vm_id;
}

// No RefreshMachineStatesFromSimulator — see RefreshMachineStatesFromSimulator
// comment for why shadow load state must not be overwritten here.
void Scheduler::NewTask(Time_t now, TaskId_t task_id) {
    (void)now;

    const CPUType_t  required_cpu = RequiredCPUType(task_id);
    const VMType_t   required_vm  = RequiredVMType(task_id);
    const SLAType_t  required_sla = RequiredSLA(task_id);
    const Priority_t priority     = PriorityFromSLA(required_sla);

    SetTaskPriority(task_id, priority);

    task_states[task_id] = TaskState{
        task_id,
        required_cpu,
        required_vm,
        required_sla,
        GetTaskMemory(task_id),
        IsTaskGPUCapable(task_id),
        priority,
        false,      // assigned
        false,      // completed
        VMId_t(-1),
        0,          // retry_count
        false       // placement_failed
    };

    tasks_seen++;

    if(!TryPlaceTask(task_id)) {
        PromoteForTask(task_id);
        EnqueueRetry(task_id);
    }
}

void Scheduler::PeriodicCheck(Time_t now) {
    RefreshMachineStatesFromSimulator();
    AdjustTiers(now);
    ProcessRetryQueue(now);
}

void Scheduler::SLAWarn(Time_t now, TaskId_t task_id) {
    (void)task_id;
    ProcessRetryQueue(now);
}

void Scheduler::Shutdown(Time_t time) {
    unsigned final_running = 0, final_intermediate = 0, final_off = 0;
    for(const auto machine_id : machines) {
        const auto it = machine_tier.find(machine_id);
        if(it == machine_tier.end()) continue;
        switch(it->second) {
            case MachineTier::Running:      final_running++;      break;
            case MachineTier::Intermediate: final_intermediate++; break;
            case MachineTier::SwitchedOff:  final_off++;          break;
        }
    }

    cout << "E-Eco Scheduler report" << endl;
    cout << "Tasks seen:              " << tasks_seen            << endl;
    cout << "Tasks completed:         " << tasks_completed       << endl;
    cout << "Successful placements:   " << successful_placements << endl;
    cout << "Retry enqueues:          " << retry_enqueues        << endl;
    cout << "Retry attempts:          " << retry_attempts        << endl;
    cout << "Placement failures:      " << placement_failures    << endl;
    cout << "VMs created:             " << vms_created           << endl;
    cout << "Tier promotions:         " << tier_promotions       << endl;
    cout << "Tier demotions:          " << tier_demotions        << endl;
    cout << "Final tier — Running: "    << final_running
         << " Intermediate: "           << final_intermediate
         << " Off: "                    << final_off             << endl;
    cout << "SLA0 tasks still queued: " << queued_sla0_count     << endl;
    cout << "SLA1 tasks still queued: " << queued_sla1_count     << endl;
    cout << "Failed task IDs: ";
    if(failed_task_ids.empty()) {
        cout << "none";
    } else {
        for(size_t i = 0; i < failed_task_ids.size(); i++) {
            if(i > 0) cout << ",";
            cout << failed_task_ids[i];
        }
    }
    cout << endl;

    for(auto &kv : vm_states) {
        const VMState &vm = kv.second;
        const auto machine_it = machine_views.find(vm.machine_id);
        if(machine_it == machine_views.end()) continue;
        if(machine_it->second.s_state != S0) continue;  // ← add this
        VM_Shutdown(kv.first);
    }
    SimOutput("SimulationComplete(): finished at time " + to_string(time), 4);
}

// Shadow load state decremented here — no simulator refresh.
void Scheduler::TaskComplete(Time_t now, TaskId_t task_id) {
    SimOutput("Scheduler::TaskComplete(): task " + to_string(task_id)
              + " complete at " + to_string(now), 4);

    const auto task_it = task_states.find(task_id);
    if(task_it == task_states.end()) return;
    if(task_it->second.completed)    return;

    TaskState &task = task_it->second;
    task.completed = true;
    tasks_completed++;

    if(!task.assigned) return;

    const VMId_t vm_id = task.assigned_vm;
    const auto vm_it = vm_states.find(vm_id);
    if(vm_it == vm_states.end()) {
        task.assigned    = false;
        task.assigned_vm = VMId_t(-1);
        return;
    }

    VMState &vm = vm_it->second;

    if(vm.tracked_memory_footprint >= task.required_memory) {
        vm.tracked_memory_footprint -= task.required_memory;
    } else {
        vm.tracked_memory_footprint = 0;
    }

    const auto machine_it = machine_views.find(vm.machine_id);
    if(machine_it != machine_views.end()) {
        MachineStateView &machine = machine_it->second;
        if(machine.active_task_count > 0) machine.active_task_count--;
        if(machine.tracked_memory_used >= task.required_memory) {
            machine.tracked_memory_used -= task.required_memory;
        } else {
            machine.tracked_memory_used = 0;
        }
    }

    task.assigned    = false;
    task.assigned_vm = VMId_t(-1);

    if(!retry_queue.empty()) {
        ProcessRetryQueue(now);
    }
}


// =============================================================================
// SECTION 7 — Public interface
// =============================================================================

static Scheduler Scheduler;

void InitScheduler() {
    SimOutput("InitScheduler(): initializing", 4);
    Scheduler.Init();
}

void HandleNewTask(Time_t time, TaskId_t task_id) {
    SimOutput("HandleNewTask(): task " + to_string(task_id)
              + " at time " + to_string(time), 4);
    Scheduler.NewTask(time, task_id);
}

void HandleTaskCompletion(Time_t time, TaskId_t task_id) {
    SimOutput("HandleTaskCompletion(): task " + to_string(task_id)
              + " at time " + to_string(time), 4);
    Scheduler.TaskComplete(time, task_id);
}

void MemoryWarning(Time_t time, MachineId_t machine_id) {
    SimOutput("MemoryWarning(): machine " + to_string(machine_id)
              + " at time " + to_string(time), 0);
}

void MigrationDone(Time_t time, VMId_t vm_id) {
    SimOutput("MigrationDone(): VM " + to_string(vm_id)
              + " at time " + to_string(time), 4);
    Scheduler.MigrationComplete(time, vm_id);
}

void SchedulerCheck(Time_t time) {
    SimOutput("SchedulerCheck(): at time " + to_string(time), 4);
    Scheduler.PeriodicCheck(time);
}

void SimulationComplete(Time_t time) {
    cout << "SLA violation report" << endl;
    cout << "SLA0: " << GetSLAReport(SLA0) << "%" << endl;
    cout << "SLA1: " << GetSLAReport(SLA1) << "%" << endl;
    cout << "SLA2: " << GetSLAReport(SLA2) << "%" << endl;
    cout << "Total Energy " << Machine_GetClusterEnergy() << "KW-Hour" << endl;
    cout << "Simulation run finished in " << double(time)/1000000 << " seconds" << endl;
    SimOutput("SimulationComplete(): at time " + to_string(time), 4);
    Scheduler.Shutdown(time);
}

void SLAWarning(Time_t time, TaskId_t task_id) {
    Scheduler.SLAWarn(time, task_id);
}

void StateChangeComplete(Time_t time, MachineId_t machine_id) {
    Scheduler.HandleMachineWake(time, machine_id);
}